import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-qLk6+flbM6mW4WpPz0DGB7pQx9V9vH8JQm8Xb7GtF9ZUe1wN6QJzZJp9C6d8i/0z5aDZt7y8Wapn6Fv8JW5OJw=="
          crossorigin="anonymous"
        />
      </head> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
